apiVersion: v1
kind: ServiceAccount
metadata:
  name:  akka-simple-cluster
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: akka-simple-cluster
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: akka-simple-cluster
subjects:
- kind: ServiceAccount
  name:  akka-simple-cluster
  namespace: default
roleRef:
  kind: ClusterRole
  name: akka-simple-cluster
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-cluster
spec:
  replicas: 5
  selector:
    matchLabels:
      app: akka-simple-cluster
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: akka-simple-cluster
    spec:
      containers:
      - image: gabbi/akka-k8s-2:0.1
        imagePullPolicy: IfNotPresent
        name: akka-simple-cluster
        env:
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
        ports:
        - name: remoting
          containerPort: 2551
        - name: api
          containerPort: 8080
        - name: management
          containerPort: 8558
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
      serviceAccount: akka-simple-cluster