apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: akka-producer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: akka-producer
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: akka-cluster
        image: gabbi/akka-cluster:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: "384Mi"
            cpu: "200m"        
        ports:
        - containerPort: 2551
          name: port
        envFrom:
        - configMapRef:
            name: akka-cluster
        env:
        - name: ROLES
          value: "producer"
        - name: HOST
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP          
        command:
          - "/bin/sh"
          - "-c"
          - "java -jar $VM_OPTS *assembly*.jar"
